//! The model runtime, checked against the Python one it replaces.
//!
//! This is the part of the port that can be pinned exactly. No audio is
//! involved: the same pseudo-random feature matrix goes into both runtimes, so
//! any disagreement beyond floating-point noise is a bug in the tree walk, the
//! link function, or the `.npz` reader — and every later stage is built on top
//! of those. The reference is regenerated by `rust/parity/gbm_reference.py`.

use mixlyzer_phrase::gbm::HistGradientBoosting;
use mixlyzer_phrase::npz;
use mixlyzer_phrase::testsig;

fn reference() -> serde_json::Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/gbm_reference.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {}: {e}", path.display()));
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn shipped_model() -> mixlyzer_phrase::npz::Npz {
    let path = mixlyzer_phrase::model::find_default_model(env!("CARGO_MANIFEST_DIR"))
        .expect("the shipped weights should be findable from the crate directory");
    npz::parse(&std::fs::read(path).expect("read weights")).expect("parse weights")
}

fn numbers(value: &serde_json::Value) -> Vec<Vec<f64>> {
    value
        .as_array()
        .expect("a 2-D array")
        .iter()
        .map(|row| {
            row.as_array()
                .expect("a row")
                .iter()
                .map(|v| v.as_f64().expect("a number"))
                .collect()
        })
        .collect()
}

fn check_stage(stage: &str) {
    let fixture = reference();
    let archive = shipped_model();
    let model = HistGradientBoosting::from_npz(&archive, stage).expect("load ensemble");

    let seed = fixture["seed"].as_u64().expect("seed") as u32;
    let rows = fixture["rows"].as_u64().expect("rows") as usize;
    let cols = fixture[format!("{stage}_columns")].as_u64().expect("columns") as usize;
    let x = testsig::random_matrix(seed, rows, cols);

    let checksum = fixture[format!("{stage}_checksum")].as_f64().expect("checksum");
    assert!(
        (testsig::matrix_checksum(&x) - checksum).abs() < 1e-9,
        "the Rust and Python matrix generators have drifted apart; \
         comparing outputs would be meaningless"
    );

    let expected_classes: Vec<String> = fixture[format!("{stage}_classes")]
        .as_array()
        .expect("classes")
        .iter()
        .map(|v| v.as_str().expect("a class name").to_string())
        .collect();
    assert_eq!(model.classes, expected_classes, "{stage} class order");

    let expected_raw = numbers(&fixture[format!("{stage}_raw")]);
    let expected_proba = numbers(&fixture[format!("{stage}_proba")]);
    let expected_predict: Vec<&str> = fixture[format!("{stage}_predict")]
        .as_array()
        .expect("predictions")
        .iter()
        .map(|v| v.as_str().expect("a label"))
        .collect();

    for (index, row) in x.iter().enumerate() {
        let raw = model.raw_predict_row(row);
        assert_eq!(raw.len(), expected_raw[index].len(), "{stage} raw width");
        for (column, (got, want)) in raw.iter().zip(&expected_raw[index]).enumerate() {
            assert!(
                (got - want).abs() <= 1e-12 * want.abs().max(1.0),
                "{stage} raw[{index}][{column}]: {got} != {want}"
            );
        }
        let proba = model.predict_proba_row(row);
        for (column, (got, want)) in proba.iter().zip(&expected_proba[index]).enumerate() {
            assert!(
                (got - want).abs() <= 1e-12,
                "{stage} proba[{index}][{column}]: {got} != {want}"
            );
        }
        assert_eq!(
            model.predict_label(row),
            expected_predict[index],
            "{stage} prediction for row {index}"
        );
    }
}

#[test]
fn the_boundary_ensemble_matches_the_python_runtime() {
    check_stage("boundary");
}

#[test]
fn the_label_ensemble_matches_the_python_runtime() {
    check_stage("label");
}

#[test]
fn the_shipped_model_loads_with_the_expected_shape() {
    let path = mixlyzer_phrase::model::find_default_model(env!("CARGO_MANIFEST_DIR"))
        .expect("shipped weights");
    let model = mixlyzer_phrase::PhraseModel::load(path).expect("load model");
    assert_eq!(model.boundary.n_raw(), 1, "boundary detection is binary");
    assert_eq!(model.label.n_classes(), 8);
    assert_eq!(model.labels.len(), 8);
    assert_eq!(model.transition.len(), 10, "8 labels plus START and END");
    assert!(model.transition.iter().all(|row| row.len() == 10));
    assert_eq!(model.settings.min_distance_beats, 16);
    assert_eq!(model.settings.boundary_lengths_beats, vec![16, 32, 64, 128]);
}
